CREATE TABLE ADMINREG(
AID INT NOT NULL IDENTITY(1,1) ,
NAME VARCHAR(255),
AGE INT,
GENDER VARCHAR(255),
HEIGHT VARCHAR(255),
WE VARCHAR(255),
BL VARCHAR(255),
MOBILE VARCHAR(255) UNIQUE,
EMAIL VARCHAR(255) UNIQUE,
NID VARCHAR(255)  UNIQUE,
PASS VARCHAR(255),
PIC VARCHAR(255),
)
Select *from ADMINREG

INSERT INTO ADMINREG(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC) 
VALUES('Mr.Hiru Kazi',38,'M','165','85','O+','01921234124','hiru38@gmail.com','2343414521','Hiru0038','C:\Users\MN\OneDrive\Documents\NetBeansProjects\Gym\src\gym\Pic\heru.jpg')





CREATE TABLE MENTOR(
TID INT NOT NULL IDENTITY(1601,1) ,
NAME VARCHAR(255),
AGE INT,
GENDER VARCHAR(255),
HEIGHT VARCHAR(255),
WE VARCHAR(255),
BL VARCHAR(255),
MOBILE VARCHAR(255) UNIQUE,
EMAIL VARCHAR(255) UNIQUE,
NID VARCHAR(255)  UNIQUE,
PASS VARCHAR(255),
PIC VARCHAR(255),
SHIFT VARCHAR(255),
PAC VARCHAR(255)


)
SELECT *FROM MENTOR

INSERT INTO MENTOR(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC,SHIFT,PAC) 
VALUES('Mr.Manik Azad',34,'M','155','80','A+','01778443460','manikazad64@gmail.com','4526519844','Manik034','C:\Users\MN\OneDrive\Documents\NetBeansProjects\Gym\src\gym\Pic\manik.png','07:00 AM-10:00 AM','Happy Member')

INSERT INTO MENTOR(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC,SHIFT,PAC) 
VALUES('Mr.Rabbi',36,'M','175','90','B+','01778446540','rabbi36@gmail.com','4526519866','Rabbi036','C:\Users\MN\OneDrive\Documents\NetBeansProjects\Gym\src\gym\Pic\rabbi.png','10:00 AM-01:00 PM','Super Saver')


INSERT INTO MENTOR(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC,SHIFT,PAC) 
VALUES('Mr. Asadul Islam Milon',35,'M','178','89','A+','01778443480','milon35@gmail.com','4526519888','Milon035','C:\Users\MN\OneDrive\Documents\NetBeansProjects\Gym\src\gym\Pic\milon.jpg','01:00 PM-04:00 PM','Elite Member')


INSERT INTO MENTOR(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC,SHIFT,PAC) 
VALUES('Mr.Shahin',21,'M','160','50','O+','01712588667','shahin21@gmail.com','4526519821','Shahin21','C:\Users\MN\OneDrive\Documents\NetBeansProjects\Gym\src\gym\Pic\sahin.jpg','04:00 PM-08:00 PM','Holiday Member')


INSERT INTO MENTOR(NAME,AGE,GENDER,HEIGHT,WE,BL,MOBILE,EMAIL,NID,PASS,PIC,SHIFT,PAC) 
VALUES('Ms. Nighat Sultana',30,'F','158','60','A+','01921234124','nighat30@gmail.com','4526519830','Nighat30','C:\Users\MN\OneDrive\Documents\NetBeansProjects\Gym\src\gym\Pic\heru.jpg','08:00 PM-11:00 PM','Female Member')



CREATE TABLE TRAINEREG(
TID INT NOT NULL IDENTITY(1101,1) ,
NAME VARCHAR(255),
AGE INT,
GENDER VARCHAR(255),
HEIGHT VARCHAR(255),
WE VARCHAR(255),
BL VARCHAR(255),
MOBILE VARCHAR(255) UNIQUE,
EMAIL VARCHAR(255) UNIQUE,
NID VARCHAR(255)  UNIQUE,
PASS VARCHAR(255),
PIC VARCHAR(255),
TNAME VARCHAR(255),
M_TID INT,
SHIFT VARCHAR(255),
PAC VARCHAR(255),
M_SHIFT VARCHAR(255)

)


CREATE TABLE MEMBEREG(
MID INT NOT NULL IDENTITY(2201,1) ,
NAME VARCHAR(255),
AGE INT,
GENDER VARCHAR(255),
HEIGHT VARCHAR(255),
WE VARCHAR(255),
BL VARCHAR(255),
MOBILE VARCHAR(255) UNIQUE,
EMAIL VARCHAR(255) UNIQUE,
NID VARCHAR(255)  UNIQUE,
PASS VARCHAR(255),
PIC VARCHAR(255),
TNAME VARCHAR(255),
TID INT,
BILL INT,
PAC VARCHAR(255)


)
Select * from MEMBEREG
ALTER TABLE MEMBEREG
ADD AOD DATE

ALTER TABLE TRAINEREG
ADD DOJ DATE

ALTER TABLE MENTOR
ADD DOJ DATE


UPDATE MENTOR SET DOJ='2016-01-01' WHERE TID=1601
UPDATE MENTOR SET DOJ='2016-04-01' WHERE TID=1602
UPDATE MENTOR SET DOJ='2016-06-01' WHERE TID=1603
UPDATE MENTOR SET DOJ='2016-12-01' WHERE TID=1604
UPDATE MENTOR SET DOJ='2016-01-01' WHERE TID=1605



ALTER TABLE MEMBEREG
ADD CONSTRAINT PK_M PRIMARY KEY (MID)

ALTER TABLE TRAINEREG
ADD CONSTRAINT PK_T PRIMARY KEY (TID)


ALTER TABLE ADMINREG
ADD CONSTRAINT PK_A PRIMARY KEY (AID)


ALTER TABLE MENTOR
ADD CONSTRAINT PK_MT PRIMARY KEY (TID)



ALTER TABLE MEMBEREG
ADD CONSTRAINT FK_MM FOREIGN KEY (TID) REFERENCES MENTOR (TID)



CREATE TABLE ALLOT(
MN_ID INT,
FR_ID INT,
FR_NAME VARCHAR(255),
MEM_ID INT,
MEM_NAME VARCHAR(255)


)


ALTER TABLE ALLOT
ADD CONSTRAINT MEM_UNI UNIQUE (MEM_ID)


ALTER TABLE MENTOR
ADD SALARY INT 


UPDATE MENTOR SET SALARY=25000 WHERE TID=1601
UPDATE MENTOR SET SALARY=30000 WHERE TID=1602
UPDATE MENTOR SET SALARY=28000 WHERE TID=1603
UPDATE MENTOR SET SALARY=10000 WHERE TID=1604
UPDATE MENTOR SET SALARY=25000 WHERE TID=1605

ALTER TABLE TRAINEREG
ADD SALARY INT 



ALTER TABLE TRAINEREG
ADD CONSTRAINT DF_SAL DEFAULT 8000 FOR SALARY


CREATE TABLE EQUIPMENT(
EID VARCHAR(255) UNIQUE,
ENAME VARCHAR(255),
CON VARCHAR(255),
PROBLEM VARCHAR(255),
LP DATE


)
ALTER TABLE EQUIPMENT
ADD ENID INT

CREATE TABLE BILLS(
MID INT,
BM  VARCHAR(50),
BA  INT,
BD  DATE

)

SELECT SUM(BA) AS 'TOTAL' FROM BILLS where BM='Jan22'
SELECT SUM(SALARY) AS 'TOTALM' FROM MENTOR 
SELECT SUM(SALARY) AS 'TOTALT' FROM TRAINEREG


CREATE TABLE EXPENSE (
 MOY VARCHAR(15) UNIQUE ,
 TP INT,
 CB INT,
 IB INT,
 WB INT,
 NB INT,
 ACC INT,
 RENT INT,
 OTHERS INT
 
 )
 
 
 CREATE TABLE ROUTINE(
WN VARCHAR(255),
SE INT,
REPS INT,
AD DATE,
WEE VARCHAR(20),
CON INT,
MID INT,
TID INT

)



select * from ADMINREG;
select * from TRAINEREG;

select * from ALLOT;
select * from BILLS;
select * from EQUIPMENT;
select * from EXPENSE;
select * from MENTOR;
select * from ROUTINE;









