CREATE TABLE STUDENTS(
ID INT,
NAME VARCHAR(255),
CITY VARCHAR(255),
PHONE VARCHAR(255) 	
)
--SELECT * FROM STUDENTS
INSERT INTO STUDENTS VALUES(1001,'KARIM','DHAKA', '01619253055')
SELECT * FROM STUDENTS			  --DISPLAY OUTPUT

INSERT INTO STUDENTS VALUES(1002,'RAHIM','DHAKA', '01389253055'),
(1003,'AFIF','CTG', '01389253055'),(1002,'ABC','CTG', '01389253055')

SELECT * FROM STUDENTS			  --DISPLAY OUTPUT

DELETE FROM STUDENTS WHERE NAME = 'RAHIM'	   --DELETE ALL ROWS THAT CONTAINS NAME RAHIM

UPDATE STUDENTS SET ID = '1002' WHERE NAME = 'ABC'		--UPDATING THE VALUES OF ABC

SELECT CITY FROM STUDENTS		  --DISPLAY OUTPUT ONLY 'CITY'

ALTER TABLE STUDENTS
ADD EMAIL VARCHAR(255)

SELECT * FROM STUDENTS			  --DISPLAY OUTPUT

INSERT INTO STUDENTS VALUES
(1005,'AKIB','RAJSHAHI', '0133465789','AKIB@YAHOO.COM')

SELECT * FROM STUDENTS			  --DISPLAY OUTPUT

--FIND AND SHOW DUPLICATE VALUES IN STUDENT TABLE

SELECT ID,NAME,CITY,PHONE, Count(*) FROM STUDENTS  
GROUP BY ID,NAME,CITY,PHONE
HAVING Count(*) >1

SELECT * FROM STUDENTS			  --DISPLAY OUTPUT

DELETE FROM STUDENTS WHERE NAME NOT IN(
SELECT MAX(NAME) FROM STUDENTS GROUP BY ID,NAME,CITY,PHONE) 

SELECT * FROM STUDENTS			  --DISPLAY OUTPUT

DELETE FROM STUDENTS WHERE ID = 1005

INSERT INTO STUDENTS VALUES(1005,'RAFI','DHAKA','230943324','RAFI@GMAIL.COM')

/*
HAVE TO EXECUTE WHOLE STUDENTSCTE ELSE IT WILL SHOW ERROR
PARTITION BY DIVIDES THE QUERY RESULT SET INTO PARTITIONS
*/

WITH STUDENTSCTE As
(
	SELECT *, ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) AS RowNumber   --USED RowNumber VARIABLE HERE
	FROM STUDENTS
)
DELETE FROM STUDENTSCTE WHERE RowNumber>1

--SELECT * FROM STUDENTSCTE

SELECT * FROM STUDENTS

INSERT INTO STUDENTS VALUES(1006,'ABC','DHAKA','230943324','ABC@GMAIL.COM')


WITH STUDENTSCTE As
(						   --USED ROWNUMBER1 VARIABLE HERE, VARIABLE CAN'T BE SAME LIKE PREVIOUS
	SELECT *, ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY NAME) AS ROWNUMBER1	 
	FROM STUDENTS
)
--SELECT * FROM STUDENTSCTE
DELETE FROM STUDENTSCTE WHERE ROWNUMBER1>1

SELECT * FROM STUDENTS

SELECT * FROM STUDENTS ORDER BY ID	  --SORT BY ID

SELECT * FROM STUDENTS ORDER BY ID ASC	  --SORT BY ID   IN ASCENDING ORDER

SELECT * FROM STUDENTS ORDER BY ID DESC	  --SORT BY ID   IN DESCENDING ORDER

SELECT * FROM STUDENTS ORDER BY NAME  --SORT BY NAME


SELECT DISTINCT CITY FROM STUDENTS;	  --SELECT DISTINCT CITY


--SELECT NAME FROM STUDENTS WHERE NAME = 'ABC'
--LIMIT 1,4;

SELECT * FROM STUDENTS


ALTER TABLE STUDENTS
ALTER COLUMN PHONE INT		--CHANGE PHONE COLUMN FROM VARCHAR TO INT


ALTER TABLE STUDENTS		--ADDED COUNTRY COLUMN
ADD COUNTRY VARCHAR(255)

SELECT * FROM STUDENTS		

ALTER TABLE STUDENTS		--DROPED COUNTRY COLUMN
DROP COLUMN COUNTRY 

SELECT * FROM STUDENTS		

 