DROP Table R
DROP Table S
DROP Table T

CREATE TABLE R(A INT,B VARCHAR(255))

Insert into R values(1,'a')
Insert into R values(2,'b')
Insert into R values(3,'c')

SELECT * FROM R

CREATE TABLE S(B VARCHAR(255), C VARCHAR(255))

Insert into S values('a','x')
Insert into S values('b','y')
Insert into S values('c','z')

SELECT * FROM S

CREATE TABLE T(C VARCHAR(255),A INT)

Insert into T values('x',2)
Insert into T values('y',3)
Insert into T values('z',4)

SELECT * FROM T

drop table R1
drop table R2


-- 1st
SELECT * FROM R WHERE EXISTS (SELECT 1 FROM T WHERE R.A = T.A)

SELECT * INTO R1 FROM (SELECT * FROM R WHERE EXISTS (SELECT 1 FROM T WHERE R.A = T.A))

WITH CTE AS (SELECT * FROM R WHERE EXISTS (SELECT 1 FROM T WHERE R.A = T.A))
SELECT * INTO R1 FROM CTE

SELECT * FROM R1

-- 2nd
drop table S1

WITH CTE AS (SELECT * FROM S WHERE EXISTS (SELECT 1 FROM R1 WHERE S.B = R1.B))
SELECT * INTO S1 FROM CTE

SELECT * FROM S1


-- 3rd
drop table T1

WITH CTE AS (SELECT * FROM T WHERE EXISTS (SELECT 1 FROM S1 WHERE T.C = S1.C))
SELECT * INTO T1 FROM CTE

SELECT * FROM T1



-- 4th
drop table R2

WITH CTE AS (SELECT * FROM R1 WHERE EXISTS (SELECT 1 FROM T1 WHERE R1.A = T1.A))
SELECT * INTO R2 FROM CTE

SELECT * FROM R2


-- 5th
drop table S2

WITH CTE AS (SELECT * FROM S1 WHERE EXISTS (SELECT 1 FROM R2 WHERE S1.B = R2.B))
SELECT * INTO S2 FROM CTE

SELECT * FROM S2



-- 6th
drop table T2

WITH CTE AS (SELECT * FROM T1 WHERE EXISTS (SELECT 1 FROM S2 WHERE T1.C = S2.C))
SELECT * INTO T2 FROM CTE

SELECT * FROM T2


-- 7th


WITH CTE AS (SELECT * FROM R2 WHERE EXISTS (SELECT 1 FROM T2 WHERE R2.A = T2.A))
SELECT * INTO R3 FROM CTE

SELECT * FROM R3
