SET SERVEROUTPUT ON;

------STATEMENT LEVEL TRIGGER-------
/*
CREATE OR REPLACE TRIGGER HELLO4 
AFTER UPDATE OF TAKA
ON MONEY
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Hi4');
END;
/
UPDATE MONEY SET TAKA=1000 WHERE ID=10;

--update money set name='Z' where id=3;
--update money set taka=1000 where id=3;

*/

-----ROW LEVEL TRIGGER-----

CREATE OR REPLACE TRIGGER HELLO5 
AFTER UPDATE 
OF TAKA
ON MONEY
FOR EACH ROW
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO5');
END;
/

--UPDATE MONEY SET TAKA=1000 WHERE ID=10;
UPDATE MONEY SET TAKA=1000;
--SELECT * FROM MONEY;


/*
CREATE OR REPLACE TRIGGER HELLO6 
BEFORE UPDATE 
OF TAKA
ON MONEY
FOR EACH ROW
DECLARE
	A money.id%TYPE;
	B money.name%TYPE;
	C money.taka%TYPE;
BEGIN
	A := :OLD.ID;
	B := :OLD.NAME;
	C := :OLD.TAKA;
	INSERT INTO MONEY1 VALUES(A, B, C);
END;
/
UPDATE MONEY SET TAKA=2000 WHERE ID=1;
*/
--SELECT * FROM MONEY;
--SELECT * FROM MONEY1;

